# Generated by Django 6.0 on 2025-12-14 04:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(help_text='One-line description for the index page', max_length=255)),
                ('content', ckeditor.fields.RichTextField(help_text='Detailed project overview')),
                ('tech_stack', models.CharField(help_text='e.g. Django, React, Postgres', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed')], default='running', max_length=20)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('repo_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
