# Generated by Django 6.0 on 2025-12-14 07:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_project_view_count_analyticsevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='I am a Product Designer and Full-Stack Engineer.', max_length=200)),
                ('bio', ckeditor.fields.RichTextField(help_text='Main long-form bio content.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('twitter_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('job_current', models.CharField(default='Stripe', max_length=100)),
                ('job_current_role', models.CharField(default='Senior Product Designer', max_length=100)),
                ('job_current_date', models.CharField(default='2020 — Present', max_length=50)),
                ('job_previous', models.CharField(blank=True, default='Vercel', max_length=100)),
                ('job_previous_role', models.CharField(blank=True, default='Frontend Engineer', max_length=100)),
                ('job_previous_date', models.CharField(blank=True, default='2018 — 2020', max_length=50)),
                ('capabilities', models.CharField(default='React, Next.js, Django, PostgreSQL, AWS, Figma, System Design', help_text='Comma separated list', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'About Profile',
            },
        ),
    ]
